background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 8
}

general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = true
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    dots_size = 0.3
    dots_spacing = 0.2
    outer_color = rgb(200,200,200)
    inner_color = rgb(30,30,30)
    font_color = rgb(255,255,255)
    fade_on_empty = false
    placeholder_text = Enter Password...
}
